database_engine: django.db.backends.mysql
database_host: 127.0.0.1
database_port: 53306
database_name: voteswap
database_user: voteswap
database_password: password
secret_key: 'i39v+-00j0_ev#mupwh=4ojxep&t_cho_z(zqmkm7cr=g313sn'
